version: 1.0.{build}
install:
    - cmd: dotnet restore
build_script:
    - dotnet pack carupano\carupano.csproj --include-symbols /p:PackageVersion=1.0.0.%APPVEYOR_BUILD_NUMBER%
    - dotnet pack carupano.azure\carupano.azure.csproj --include-symbols /p:PackageVersion=1.0.0.%APPVEYOR_BUILD_NUMBER%
    - dotnet pack carupano.sqlserver\carupano.sqlserver.csproj --include-symbols /p:PackageVersion=1.0.0.%APPVEYOR_BUILD_NUMBER%
artifacts:
    - path: '**\*.nupkg'
deploy:
    - provider: NuGet
      server: https://ci.appveyor.com/nuget/mercadolar-rt092583xhk5
      api_key:
        secure: BOzn80QmSwYOmcvWl4ai+TPuRIN60FfNhjvFC706CEI=
      skip_symbols: true
    - provider: NuGet
      api_key:
        secure: NB0A5eGcEehomtjB0mqeRunHDngjrsH4f9+2jxn/eeMsziN0WqKnS9kf5Etvfp3M
      skip_symbols: true