version: 1.0.{build}
install:
    - cmd: dotnet restore
build_script:
    - dotnet pack carupano\carupano.csproj --include-symbols --version-suffix %APPVEYOR_BUILD_NUMBER% -o .\.artifacts\
    - dotnet pack carupano.azure\carupano.azure.csproj --include-symbols --version-suffix %APPVEYOR_BUILD_NUMBER% -o .\.artifacts\
    - dotnet pack carupano.sqlserver\carupano.sqlserver.csproj --include-symbols --version-suffix %APPVEYOR_BUILD_NUMBER% -o .\.artifacts\
artifacts
    - path: '.artifacts\*.nupkg'
deploy:
    - provider: NuGet
      symbol_server: https://ci.appveyor.com/nuget/mercadolar-rt092583xhk5
      api_key:
        secure: BOzn80QmSwYOmcvWl4ai+TPuRIN60FfNhjvFC706CEI=