version: 1.0.{build}-beta
install:
    - cmd: dotnet restore
build_script:
    - dotnet pack carupano\carupano.csproj --include-symbols /p:PackageVersion=%APPVEYOR_BUILD_VERSION% /p:PackageId=Carupano
    - dotnet pack carupano.azure\carupano.azure.csproj --include-symbols /p:PackageVersion=%APPVEYOR_BUILD_VERSION% /p:PackageId=Carupano.Azure
    - dotnet pack carupano.mongodb\carupano.mongodb.csproj --include-symbols /p:PackageVersion=%APPVEYOR_BUILD_VERSION% /p:PackageId=Carupano.MongoDb
    - dotnet pack carupano.sqlserver\carupano.sqlserver.csproj --include-symbols /p:PackageVersion=%APPVEYOR_BUILD_VERSION%  /p:PackageId=Carupano.SqlServer
test_script:
    - cd carupano.unittests && dotnet xunit
    - cd ..\carupano.specs && dotnet xunit
artifacts:
    - path: '**\*.nupkg'
deploy:
    - provider: NuGet
      server: https://ci.appveyor.com/nuget/mercadolar-rt092583xhk5
      api_key:
        secure: BOzn80QmSwYOmcvWl4ai+TPuRIN60FfNhjvFC706CEI=
      skip_symbols: true
    - provider: NuGet
      api_key:
        secure: NB0A5eGcEehomtjB0mqeRunHDngjrsH4f9+2jxn/eeMsziN0WqKnS9kf5Etvfp3M
      skip_symbols: true
    - provider: GitHub
      artifact: /.*\.nupkg/           # upload all NuGet packages to release assets
      draft: false
      prerelease: false
      on:
        branch: master                # release from master branch only
        appveyor_repo_tag: true       # deploy on tag push only
